// MTProto posting via a Premium user account (gramjs / npm:telegram).
// Session string generated by scripts/gen-session.js (gramjs StringSession format).
// Uses @username for channel peer resolution — numeric chat_id requires cached access_hash.
// Photos are pre-downloaded via Deno fetch. Buffer from node:buffer ensures gramjs Buffer.isBuffer() check passes.
import { Buffer } from 'node:buffer'
import { TelegramClient, Api } from 'npm:telegram'
import { CustomFile } from 'npm:telegram/client/uploads.js'
import { StringSession } from 'npm:telegram/sessions/index.js'

export interface PostParams {
  apiId: number
  apiHash: string
  session: string
  chatId: string | number
  text: string
  entities: BotApiEntity[]
  photoUrl?: string | null
  starsAmount?: number | null
}

interface BotApiEntity {
  type: string
  offset: number
  length: number
  url?: string
  custom_emoji_id?: string
}

function toGramjsEntities(entities: BotApiEntity[]): any[] {
  return entities.flatMap((e) => {
    const { offset, length } = e
    if (e.type === 'custom_emoji' && e.custom_emoji_id) {
      return [new Api.MessageEntityCustomEmoji({ offset, length, documentId: BigInt(e.custom_emoji_id) })]
    }
    if (e.type === 'bold') return [new Api.MessageEntityBold({ offset, length })]
    if (e.type === 'italic') return [new Api.MessageEntityItalic({ offset, length })]
    if (e.type === 'text_link' && e.url) return [new Api.MessageEntityTextUrl({ offset, length, url: e.url })]
    return []
  })
}

// Downloads photo and wraps in gramjs CustomFile so gramjs can upload it directly.
// gramjs checks instanceof CustomFile — duck-typed objects are rejected with "Cannot use [object Object] as file".
async function downloadAsGramFile(url: string): Promise<CustomFile | null> {
  try {
    const resp = await fetch(url)
    if (!resp.ok) {
      console.error('[MTProto] photo download failed:', resp.status, url)
      return null
    }
    const contentType = resp.headers.get('content-type') ?? 'image/jpeg'
    const ext = contentType.includes('png') ? 'png'
      : contentType.includes('gif') ? 'gif'
      : contentType.includes('webp') ? 'webp'
      : contentType.startsWith('video/') ? 'mp4'
      : 'jpg'
    const arrayBuf = await resp.arrayBuffer()
    const buffer = Buffer.from(arrayBuf)
    return new CustomFile(`media.${ext}`, buffer.length, '', buffer)
  } catch (err) {
    console.error('[MTProto] photo download error:', String(err))
    return null
  }
}

function timeout(ms: number, label: string): Promise<never> {
  return new Promise((_, reject) =>
    setTimeout(() => reject(new Error(`${label} timed out after ${ms}ms`)), ms)
  )
}

export async function postViaMTProto(params: PostParams): Promise<{ ok: boolean; error?: string }> {
  const { apiId, apiHash, session, chatId, text, entities, photoUrl, starsAmount } = params
  const client = new TelegramClient(new StringSession(session), apiId, apiHash, {
    connectionRetries: 3,
    requestRetries: 2,
  })

  try {
    console.log('[MTProto] connecting...')
    const connectStart = Date.now()
    await Promise.race([client.connect(), timeout(20_000, 'MTProto connect')])
    console.log(`[MTProto] connected in ${Date.now() - connectStart}ms`)

    const gramEntities = toGramjsEntities(entities)
    const peer = String(chatId)

    if (starsAmount && starsAmount > 0 && photoUrl) {
      // Paid media via InputMediaPaidMedia — MTProto user account can create paid posts directly
      const gramFile = await Promise.race([downloadAsGramFile(photoUrl), timeout(10_000, 'photo download')])
      if (!gramFile) throw new Error('photo download failed for paid media')

      const uploaded = await Promise.race([
        client.uploadFile({ file: gramFile, workers: 1 }),
        timeout(60_000, 'photo upload'),
      ])

      const inputPhoto = new Api.InputMediaUploadedPhoto({ file: uploaded })
      const paidMedia = new Api.InputMediaPaidMedia({
        starsAmount: BigInt(starsAmount),
        extendedMedia: [inputPhoto],
      })

      await Promise.race([
        client.invoke(new Api.messages.SendMedia({
          peer,
          media: paidMedia,
          message: text || '',
          randomId: BigInt(Math.floor(Math.random() * 1e15)),
          ...(gramEntities.length > 0 ? { entities: gramEntities } : {}),
        })),
        timeout(60_000, 'MTProto paid send'),
      ])
    } else if (photoUrl) {
      const gramFile = await Promise.race([downloadAsGramFile(photoUrl), timeout(10_000, 'photo download')])
      const file = gramFile ?? photoUrl

      await Promise.race([
        client.sendMessage(peer, {
          message: text || '',
          file,
          forceDocument: false,
          ...(gramEntities.length > 0 ? { formattingEntities: gramEntities } : {}),
        }),
        timeout(60_000, 'MTProto send'),
      ])
    } else {
      await Promise.race([
        client.sendMessage(peer, {
          message: text || '—',
          ...(gramEntities.length > 0 ? { formattingEntities: gramEntities } : {}),
        }),
        timeout(30_000, 'MTProto send'),
      ])
    }

    console.log('[MTProto] send OK')
    return { ok: true }
  } catch (err) {
    const errStr = String(err)
    const isTimeout = errStr.includes('timed out')
    const isAuth = errStr.includes('AUTH') || errStr.includes('SESSION') || errStr.includes('401')
    const isFlood = errStr.includes('FLOOD') || errStr.includes('429')
    console.error(`[MTProto] failed for ${chatId} [${isTimeout ? 'TIMEOUT' : isAuth ? 'AUTH' : isFlood ? 'FLOOD' : 'ERROR'}]:`, errStr)
    return { ok: false, error: errStr }
  } finally {
    try { await Promise.race([client.disconnect(), timeout(3_000, 'disconnect')]) } catch { /* ignore */ }
  }
}
